### ISSUE TITLE
[讨论]partial注释的定制化，开发环境和组件查看工具的集成

### ISSUE THREAD

**Issue by creeperyang** [creeperyang/static-site-dev#11]
先说一个具体问题，即build时应该可以一键删除所有的partial注释。这个可以通过调整代码，使生成注释的方法可配置来达到。

然后，回到这个issue的焦点：怎么和 https://github.com/jumbo/FlightBooking 集成？

[更新］partial注释在build时全部删除 0cb0341

**Comment by creeperyang** [comment]
**情况介绍**

目前的组件工具，是通过向页面（包含了组件的所有状态，且组件前后有注释帮助解析）注入脚本来完成功能。并且，为了屏蔽/透明化注入过程，内置了代理服务器。

我们需要讨论的是:
1. 在页面里罗列出某一组件所有的状态（多份html片段）肯定不是最好/最高效的，那怎么改？
2. 做一套大的高集成的开发环境，还是轻量化，功能配置化？
3. 在本开发环境里，典型的组件怎么写？尤其是有多个状态时？考虑边际情况：每种状态dom结构差别大。
4. 更多（@jumbo @shallychen @blueed @lk1607 请添加）

**Comment by creeperyang** [comment]
**看法**

首先应该讨论的是组件怎么写？这个看起来是基础问题。

考虑到前置条件——我们已经具备服务端渲染的handlebars模板，即模板通过`if/else/each`等helper（甚至更多自定义helper）已经具备定制化能力，那么组件只写一份是可行的。不同状态可以通过data来控制。

[组件分离，一份，数据控制］

---

其次，组件怎么引入到页面？

当然是通过partial（`{{> partial }}`）。

但问题关注的是多状态的组件怎么引入？原来我们是组件的多个状态同时写到页面里，并且组件也基本就是在页面里（没有分离）。现在我们分离了，并且通过parial语法引入组件的默认状态，要考虑的就是怎么引入组件的多个状态：
1. 一个当然是组件写多份，引入多次。但这肯定不方便，先放弃。
2. 组件只写一份，引入多次。这里需要为每次引入指定不同数据即可，可以通过增强partial语法达成。比如`{{> partial data=data1}} {{> partial data=data2}}`。
3. 组件只写一份，引入一次。还是通过增强partial语法，`{{> partial state=state1,state2 }}`。state1,state2去对应两份数据，本质上还是对2的增强。

以上，本质上输出到浏览器端的还是有同组件不同状态的多份html片段。那么有可能，或者说有需要只有一份html呢？

**discussion wanted!**

既然不能在html里有多份，那么组件的多个状态就只能在JS里去注册。

是不是可以这样呢？

``` html
// out page
// and default state of component A
<A-default-dom></A-default-dom>

<script>
window.components.A = {
  default: { template, data },
  state1: { template, data }, // 应该只需要一份template
  state2: { template, data } // 应该只需要一份template
};
</script>
```

看起来似乎是个可行的解决方案。

配合服务器端渲染，其实我们可以在url里传入我们希望渲染的组件列表，每个组件需要第一次显示的状态。然后在页面渲染后，页面里有如上的脚本载入了所有的组件信息，所以我们可以无刷新显示所有组件的所有状态。

**Comment by creeperyang** [comment]
``` bash
├── front/src/shared/partials
│   ├── components
│   │   ├── passenger
│   │   ├── passenger/component.json
│   │   ├── passenger/template.html
```

理想的组件结构如上所示。

我们可以在`component.json`里写上组件的所有状态。

如果所有组件都以这种形式存在，那么可以预先扫描并生成一份组件列表及组件所有状态的数据给浏览器。

**Comment by jumbo** [comment]
``` bash
├── front/src/shared/partials
│   ├── components
│   │   ├── passenger
│   │   ├── passenger/component.json
│   │   ├── passenger/template.html
```
- 采用以上方式需要设计一套假数据用以模拟状态生产环境，相对复杂，但是可以尝试，就以之前的passenger组件示例一下，看看复杂度是否在接受范围。
- 修改某个状态的时候，类似sourcemap的注释功能似乎会失去意义……

其他
- 全局的顶部导航可以添加一个组件显示隐藏的下拉。
- Server端可以不再proxy
- 文档描述下避免前后端js模版的冲突解决……
- 短地址作为接下来的改进点
