### ISSUE TITLE
支持`viewer`和`src`目录的分离

### ISSUE THREAD

**Issue by creeperyang** [creeperyang/static-site-dev#19]
比如`src`目录不在当前项目根目录下：

```
src -->  /tmp/myProject/src

viewer --> ~/sugar/front/viewer
```

怎么保证项目的可用性？（功能正常）

**Comment by creeperyang** [comment]
d096da6 已经可以做到`src`目录在任意位置而功能正常。

但是如果把`viewer`目录指定到其它目录，webpack打包过程报错，这点需要解决。

**Comment by creeperyang** [comment]
😂  艰苦卓绝的解决viewer目录分离的过程：
- [x] 尝试 把`viewer`复制到`/tmp/xxx/viewer`，结果发现loader的include指定 `/tmp/xxx/viewer`时无法加载指定loader。其实是`/tmp/xxx/viewer`并没有指向`/private/tmp/xxx/viewer`。对于symbol link的目录需要特殊处理。详情见https://github.com/webpack/webpack/issues/2587
- [x] `babel-loader`的preset无法正确加载，解决方法是：
  
  ``` js
  presets: [require.resolve('babel-preset-es2015'), xx ]
  // 代替
  presets: ['es2015', xx]
  ```
- [x] `React`等模块无法正确resolve，解决方法：
  
  ``` js
  resolve: {
      fallback: [config.modulesRoot]  // modulesRoot 是 react的安装目录： /xxx/node_modules
  },
  ```
- [x] `babel-loader`等loader无法正确resolve，因为loader是相对于代码文件来解析的。解决方法：
  
  ``` js
  resolveLoader: {
      root: config.modulesRoot
  },
  ```

**Comment by jumbo** [comment]
src分离的需求，其实就是将这个工具改造更通用，比如在另一个项目里直接npm install sugardevelop --dev 加少许配置部署好开发环境。
这里关于需求上的问题，需要斟酌下，viewer所读取的数据哪些是src，哪些是tmp（dest）。
辛苦了，边用边做，模糊的需求一点点清晰。

**Comment by creeperyang** [comment]
是这样想的，以后可以把功能提取到诸如`sugar-cli`之类的，然后

``` bash
npm i sugar-cli -g
sugar build --watch
sugar start #等等
```

目前仍然阻塞在`viewer`的分离，在加上`uglify-plugin`的情况下会报错，已经定位到错误原因，source的路径不一致问题：

``` js
sources:  { '$../../../../../private/tmp/wow/viewer/app.js': 0 }

// 取sourceMap时却是以 

$/private/tmp/wow/viewer/app.js 

// 去取
```

但什么地方开始引入这个错误的仍在调试。

**Comment by creeperyang** [comment]
错误定位：`babel-loader`以`path.relative`处理路径，`UglifyJsPlugin`的sourceMap相关却是以自己的`util.relative`来处理路径。

解决方案：目前禁用了viewer的sourceMap，待`babel-loader`解决bug后恢复。
